steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_BASE_URL=https://jussimatic-node-server-61766311353.europe-north1.run.app/'
      - '-t'
      - 'europe-north1-docker.pkg.dev/client-jussimatic/jussimatic-frontend/jussimatic-frontend:$TAG_NAME'
      - '-t'
      - 'europe-north1-docker.pkg.dev/client-jussimatic/jussimatic-frontend/jussimatic-frontend:latest'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-north1-docker.pkg.dev/client-jussimatic/jussimatic-frontend/jussimatic-frontend:$TAG_NAME'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-north1-docker.pkg.dev/client-jussimatic/jussimatic-frontend/jussimatic-frontend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'jussimatic-frontend-production'
      - '--image'
      - 'europe-north1-docker.pkg.dev/client-jussimatic/jussimatic-frontend/jussimatic-frontend:$TAG_NAME'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'europe-north1-docker.pkg.dev/client-jussimatic/jussimatic-frontend/jussimatic-frontend:$TAG_NAME'
  - 'europe-north1-docker.pkg.dev/client-jussimatic/jussimatic-frontend/jussimatic-frontend:latest'

options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 50
  logging: CLOUD_LOGGING_ONLY

timeout: '600s'
